// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

package push

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushRequest struct {
	// APN 的推送载荷内容
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// APNs bundleId
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// APN token
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// 附带的其他业务定制内容
	Ext                  []byte   `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_43081dad4a466e21, []int{0}
}
func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (dst *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(dst, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PushRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PushRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PushRequest) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PushResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_43081dad4a466e21, []int{1}
}
func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (dst *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(dst, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

func (m *PushResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "PushRequest")
	proto.RegisterType((*PushResponse)(nil), "PushResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PushServiceClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
}

type pushServiceClient struct {
	cc *grpc.ClientConn
}

func NewPushServiceClient(cc *grpc.ClientConn) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/PushService/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServiceServer is the server API for PushService service.
type PushServiceServer interface {
	Push(context.Context, *PushRequest) (*PushResponse, error)
}

func RegisterPushServiceServer(s *grpc.Server, srv PushServiceServer) {
	s.RegisterService(&_PushService_serviceDesc, srv)
}

func _PushService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PushService/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _PushService_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}

func init() { proto.RegisterFile("push.proto", fileDescriptor_push_43081dad4a466e21) }

var fileDescriptor_push_43081dad4a466e21 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xdd, 0x0a, 0x82, 0x40,
	0x10, 0x85, 0x33, 0x7f, 0xa2, 0xc9, 0x20, 0x96, 0x88, 0xa5, 0x2b, 0x11, 0x0a, 0xaf, 0xbc, 0xa8,
	0x1e, 0x24, 0xb6, 0x27, 0x30, 0x1b, 0x50, 0x0c, 0x77, 0x73, 0x66, 0xa3, 0xde, 0x3e, 0x74, 0x13,
	0xbc, 0x9b, 0xef, 0x5c, 0x9c, 0xf3, 0x0d, 0x80, 0xb1, 0x54, 0xe5, 0xa6, 0xd3, 0xac, 0x53, 0x84,
	0xd5, 0xd5, 0x52, 0xa5, 0xf0, 0x65, 0x91, 0x58, 0x48, 0x58, 0x98, 0xe2, 0xfb, 0xd4, 0xc5, 0x43,
	0x7a, 0x89, 0x97, 0xc5, 0x6a, 0x44, 0xb1, 0x85, 0x90, 0xb5, 0xa9, 0x4b, 0x39, 0x4f, 0xbc, 0x6c,
	0xa9, 0x1c, 0xb8, 0xb4, 0xc1, 0x56, 0xfa, 0x63, 0xda, 0x60, 0x2b, 0x36, 0xe0, 0xe3, 0x87, 0x65,
	0x30, 0x34, 0xf4, 0x67, 0x7a, 0x84, 0xd8, 0xcd, 0x90, 0xd1, 0x2d, 0xa1, 0xd8, 0x41, 0x44, 0x5c,
	0xb0, 0xa5, 0x61, 0x26, 0x54, 0x7f, 0x3a, 0x5d, 0x9c, 0xce, 0x0d, 0xbb, 0x77, 0x5d, 0xa2, 0x38,
	0x40, 0xd0, 0xa3, 0x88, 0xf3, 0x89, 0xe4, 0x7e, 0x9d, 0x4f, 0xbb, 0xd2, 0xd9, 0x3d, 0x1a, 0x7e,
	0x39, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x3b, 0xbe, 0x30, 0xd9, 0x00, 0x00, 0x00,
}
